[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/AI Utilities/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/AI Utilities_premium/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/AI Utilities_premium/shared/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
